### ISSUE TITLE
The freshness of data

### ISSUE THREAD

**Issue by Rangorca** [openchargemap/ocm-export#1]
Hi there,

Is this project in real-time? How often is the data refreshed? 

And, how could I get all of the OCM data? What is the max value of "maxresults"?

I will appreciate your help to answer these questions.

Thanks,
Rangorca

**Comment by webprofusion-chrisc** [comment]
Hi, this particular export of the data from OCM is currently manually refreshed. I'll perform an update shortly, thanks for the reminder.

The actual data is *not real-time*. much of the data is crowd-source (e.g. it's entered manually by volunteers around the world). We do not currently have live status information for any locations.

Your question regarding "maxresults" might be more relevant to our API and the documentation for the API is here: https://openchargemap.org/site/develop/api - there is no upper limit to maxresults but we do ask anyone using the API to be cautious of downloading the entire dataset via our API unnecessarily [the data set is over 120MB].

**Comment by Rangorca** [comment]
Thank you for the elaboration.
