### ISSUE TITLE
Export request

### ISSUE THREAD

**Issue by Goule** [openchargemap/ocm-export#2]
Hello, 

It is possible to have a data update ? 

Thanks for the export repo ! 

Best

**Comment by floriangbh** [comment]
Hello, I'm also interested in an update! Thanks :)

**Comment by webprofusion-chrisc** [comment]
Hi, sorry I missed this, yes I'll look into getting an update, this isn't automated currently and there are some changes required to update it.

**Comment by floriangbh** [comment]
Thanks !

**Comment by webprofusion-chrisc** [comment]
This has been updated now. We still need to automate this, but git struggles to perform these updates.
